### ISSUE TITLE
Add HTTPS Support

### ISSUE THREAD

**Issue by rajdhandus** [htmldriven/cors-proxy#24]
github.io pages don't accept calls to HTTP endpoints anymore. adding https support for "cors-proxy.htmldriven.com" will help deploy github.io pages with outbound https calls to "cors-proxy.htmldriven.com"

**Comment by rebendajirijr** [comment]
So you want the cors-proxy to be available at https://cors-proxy.htmldriven.com?

**Comment by rajdhandus** [comment]
yes please..

**Comment by rebendajirijr** [comment]
I've added HTTPS support. You can try it.

**Comment by rajdhandus** [comment]
https://cors-proxy.htmldriven.com/?url=https://api.eventful.com/json/events/search?q=music&t=2018-05-11&l=28262&within=20&units=miles&app_key=xxxxxxxxxxx 
<img width="1064" alt="screen shot 2018-05-11 at 8 15 13 am" src="https://user-images.githubusercontent.com/6888014/39923868-7a1ac71c-54f3-11e8-8c63-017f47a55079.png">
- doesn't seem to be working

**Comment by rebendajirijr** [comment]
I've missunderstand your problem. You want API calls to support https, not cors-proxy website.

**Comment by rebendajirijr** [comment]
@rajdhandus api should work again. I've uploaded newer version of cors-proxy yesterday, but made some deployment mistakes which I've fixed now. Try it.

**Comment by rajdhandus** [comment]
thank you! it works now...
