### ISSUE TITLE
Cors-proxy Requests are blocked by CORS?

### ISSUE THREAD

**Issue by Arxero** [htmldriven/cors-proxy#25]
Hello, Jiri
About a week ago I have found your website and decided to use it to accomplish something that I have an idea in my [forum](http://awesomecs.syntrwave.com/). In other words to make it better by writing a js function by myself to extract direct URL from an image uploaded throughout the [postimage exstension](https://postimages.org/phpbb) for phpbb forums and then display the full resolution image on my forum. I good for me I have accomplished with lots of try and errors (I am still beginner at js), but today I have noticed that your website seems now to require cors, headers to be able to use your proxy cors, so it kinda defeats the purpose of the service to use it as  a proxy to reach postimage server.
It shows me this error as a response:
`Failed to load http://cors-proxy.htmldriven.com/?url=https://postimg.cc/image/mk56q648t/: Redirect from 'http://cors-proxy.htmldriven.com/?url=https://postimg.cc/image/mk56q648t/' to 'https://cors-proxy.htmldriven.com/?url=https://postimg.cc/image/mk56q648t/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access.` 
I would be glad if you can help me in any way possible, thanks.

**Comment by rebendajirijr** [comment]
@Arxero I've no problem with the request being tested, see http://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fcors-proxy.htmldriven.com%2F%3Furl%3Dhttp%3A%2F%2Fpostimg.cc%2Fimage%2Fmk56q648t%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote.

Make sure, you use HTTPS in cors-proxy.htmldriven.com as it's being enforced now.

**Comment by Arxero** [comment]
Ow yeah man, it was from that "s".Thanks a bunch now it works again as it used to. @rebendajirijr :)
