### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by ashleedawg** [htmldriven/cors-proxy#28]
The demo located at https://cors-proxy.htmldriven.com seems to be broken.

Not sure whether this is related to the site's Let's Encrypt SSL certificate, which expired August 2021.

**Comment by rebendajirijr** [comment]
@ashleedawg fixed

**Comment by Jimbolino** [comment]
its down again :)

**Comment by rebendajirijr** [comment]
> its down again :)

It's up again @Jimbolino :)
